version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  flask-app:
    build:
      context: ./flask-app
    container_name: flask_app
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  streamlit-app:
    build:
      context: ./streamlit-app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    networks:
      - app_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

volumes:
  mongodb_data:

networks:
  app_network:
